# Change these first
owner: RadovanTomik # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: BBMRI-ERIC
    url: https://bbmri-eric.eu
  - name: Directory
    url: https://directory.bbmri-eric.eu
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  theme: light
  baseUrl: /status 
  logoUrl: https://www.bbmri-eric.eu/wp-content/uploads/favicon.png
  name: BBMRI-ERIC Status
  introTitle: "**BBMRI-ERIC STATUS BOARD**"
  introMessage: Service availability
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
